import type { Metadata } from "next";

import { Events } from "@src/components";

export const metadata: Metadata = {
	title: "Event Discovery & Ticketing Platform",
	description: "Generated by create next app",
};

export default function Home() {
	return <Events />;
}
